<?php
/**
 * @project Bridge shoppingcart
 * Admin category page template
 */
?>
<div class="row">
<div class="col-lg-12">
            <h1>Category <small></small></h1>
            <ol class="breadcrumb">
                <li class="active"><i class="fa fa-dashboard"></i> Manage category</li>
            </ol>
            <div class="alert alert-success alert-dismissable">            
            <a href="index.php?page=new-category" class="btn btn-primary" id="category-new">New category +</a>
            </div>
            <?php if($categories) { ?>
            <div class="table-responsive" id="category-list">
              <table class="table table-bordered table-hover table-striped tablesorter">
                <thead>
                  <tr>                    
                    <th>Name <i class="fa fa-sort"></i></th>
                    <th>Status <i class="fa fa-sort"></i></th>
                    <th>Edit <i class="fa"></i></th>
                    <th>Remove <i class="fa"></i></th>
                  </tr>
                </thead>
                <tbody>
                    <?php  while ($row = mysql_fetch_assoc($categories)) { ?>
                  <tr>                    
                    <td><?php echo $row['name']?></td>
                    <td><?php echo ($row['status'] == 1) ? 'Enabled':'Disabled'; ?></td>
                    <td><a class="btn btn-success"  id="category-edit" href="index.php?page=edit-category&id=<?php echo $row['id'];?>">Edit</a></td>
                    <td><a class="btn btn-danger" id="category-delete" href="index.php?page=delete-category&id=<?php echo $row['id'];?>">Delete</a></td>
                  </tr>
                    <?php } ?>
                </tbody>
              </table>
            </div>
            <?php } ?>
        </div>
</div>